import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "@/app/globals.css";
import {Providers} from "@/app/providers"
import HomeHeader from '@/app/components/HomeHeader'
import {MetamaskProvider} from "@/app/hooks/useMetamask"

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Metamask Invoke",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en" >
        <body >
        <Providers>
            <MetamaskProvider>
                <HomeHeader></HomeHeader>
                {children}
            </MetamaskProvider>
        </Providers>


        </body>
        </html>
    );
}
